package httpapi

import (
	"bytes"
	"html/template"
	"net/http"
	"strconv"
)

// The server-rendered login form (arch §8.2, impl-plan §3 WP-12 acceptance 6).
//
// # Why this file exists
//
// The auth gate is all-or-nothing: "with it enabled, static assets are
// protected too, so an unauthenticated visitor cannot even enumerate the SPA's
// routes" (arch §8.2, decision D-23, WP-12 acceptance 6's "including static
// assets"). That is the requirement, and middleware.go implements it literally.
//
// Taken alone it is also unsatisfiable, because arch §7.12's other sentence —
// "the SPA calls /api/auth/status first and renders a login screen" — puts the
// login screen inside the very bundle the gate refuses to serve
// (`web/src/features/auth/LoginScreen.tsx`). The two sentences can only both
// hold if the one document an unauthenticated visitor may have is generated by
// the server. That is this page: it serves no asset, embeds no build hash and
// names no client-side route, so §8.2's guarantee is intact, and it is enough
// to log in with, so §7.12's flow is reachable. Once the cookie exists the SPA
// loads normally and its own LoginScreen handles session expiry from then on.
//
// # Why it has no JavaScript
//
// arch §8.4's CSP is `default-src 'self'` with no `script-src`, so an inline
// `<script>` is refused by the product's own policy and an external one would
// be an asset the gate must not serve. A plain HTML form is therefore the only
// login mechanism that works here — which is why `POST /api/auth/login` accepts
// `application/x-www-form-urlencoded` in addition to the JSON body of §7.12
// (authhandlers.go). `style-src` does allow `'unsafe-inline'`, so the styling
// below is legal as written.
//
// # Why it is a 401 rather than a redirect
//
// The status has to stay 401 so that a client which is not a browser still sees
// the correct code, and so that the URL the visitor typed is still in the
// address bar after logging in.

// loginPageData is the template's input. Deliberately tiny: a login page that
// reflected anything from the request would be a place to inject.
type loginPageData struct {
	// Action is `{base_path}/api/auth/login`, absolute so the form works from
	// any client-side route depth (NFR-SEC-003).
	Action string
	// Message is a fixed string chosen by loginMessage — never the raw error,
	// never anything the client supplied.
	Message string
}

// loginPageTemplate is parsed once at init; html/template's contextual escaping
// covers the two interpolations.
var loginPageTemplate = template.Must(template.New("login").Parse(`<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex, nofollow" />
<title>Oh My Manhwa-bbang</title>
<style>
:root { color-scheme: light dark; }
* { box-sizing: border-box; border-radius: 0; }
body {
  margin: 0; min-height: 100vh; display: flex; align-items: center;
  justify-content: center; padding: 24px;
  font-family: Pretendard, "Apple SD Gothic Neo", "Malgun Gothic", "Noto Sans KR", system-ui, sans-serif;
  background: #fff; color: #111;
}
main { width: 100%; max-width: 320px; }
/* A proper noun, so neither uppercased nor letter-spaced the way the old
   all-caps mark was — at 320px those two turn the name into two ragged lines. */
h1 { font-size: 20px; letter-spacing: -.01em; margin: 0 0 4px; }
p { font-size: 13px; line-height: 1.5; margin: 0 0 20px; color: #666; }
p.error { color: #c0392b; }
label { display: block; font-size: 12px; margin-bottom: 6px; color: #666; }
input, button {
  width: 100%; font: inherit; font-size: 14px; padding: 10px 12px;
  border: 1px solid #111; background: #fff; color: #111;
}
button { margin-top: 12px; background: #111; color: #fff; cursor: pointer; }
@media (prefers-color-scheme: dark) {
  body { background: #111; color: #f5f5f5; }
  p { color: #999; }
  input { background: #111; color: #f5f5f5; border-color: #f5f5f5; }
  button { background: #f5f5f5; color: #111; }
}
</style>
</head>
<body>
<main>
<h1>Oh My Manhwa-bbang</h1>
{{if .Message}}<p class="error" role="alert">{{.Message}}</p>{{else}}<p>계속하려면 비밀번호를 입력하세요.</p>{{end}}
<form method="post" action="{{.Action}}">
<label for="password">비밀번호</label>
<input id="password" name="password" type="password" autocomplete="current-password" autofocus required />
<button type="submit">로그인</button>
</form>
</main>
</body>
</html>
`))

// writeLoginPage renders the form.
//
// `Cache-Control: no-store` matters: a proxy or a browser that cached this
// document would keep showing a login form to a session that already exists.
func (s *Server) writeLoginPage(w http.ResponseWriter, r *http.Request, status int, message string) {
	var buf bytes.Buffer
	if err := loginPageTemplate.Execute(&buf, loginPageData{
		Action:  s.base + "/api/auth/login",
		Message: message,
	}); err != nil {
		// The template is a compile-time constant with two string fields, so
		// this cannot happen; if it somehow does, the envelope is still correct.
		writeError(w, r, s.log, internalErr(err))
		return
	}

	h := w.Header()
	h.Set("Content-Type", "text/html; charset=utf-8")
	h.Set("Cache-Control", "no-store")
	h.Set("Content-Length", strconv.Itoa(buf.Len()))
	w.WriteHeader(status)
	if r.Method == http.MethodHead {
		return
	}
	_, _ = w.Write(buf.Bytes())
}

// loginMessage maps a failed login onto the one sentence the form shows.
//
// It is keyed on the status rather than on the error so that the wrong-password
// case cannot accidentally start distinguishing "no password sent" from
// "incorrect password" — arch §8.2 requires those to be indistinguishable.
func loginMessage(status int) string {
	switch status {
	case http.StatusUnauthorized:
		return "비밀번호가 올바르지 않습니다."
	case http.StatusTooManyRequests:
		return "로그인 시도가 너무 많습니다. 잠시 후 다시 시도하세요."
	default:
		return "로그인하지 못했습니다."
	}
}
